services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ${SERVERS}/data/tsdproxy/config:/config
    restart: unless-stopped
    ports:
      - "9080:8080"

volumes:
  datadir:
